namespace ShieldBox.UI;

public sealed partial class LoginForm
{
    private TableLayoutPanel loginShell;
    private Panel brandPanel;
    private Panel cardHostPanel;
    private Panel loginCard;
    private Label brandLabel;
    private Label titleLabel;
    private Label subtitleLabel;
    private Label userLabel;
    private Label passwordLabel;
    private Button loginButton;
    private Label demoLabel;

    private void InitializeComponent()
    {
        this.loginShell = new TableLayoutPanel();
        this.brandPanel = new Panel();
        this.cardHostPanel = new Panel();
        this.loginCard = new Panel();
        this.brandLabel = new Label();
        this.titleLabel = new Label();
        this.subtitleLabel = new Label();
        this.userLabel = new Label();
        this.passwordLabel = new Label();
        this.loginButton = new Button();
        this.demoLabel = new Label();
        this.SuspendLayout();
        this.loginShell.ColumnCount = 2;
        this.loginShell.RowCount = 1;
        this.loginShell.Dock = DockStyle.Fill;
        this.loginShell.BackColor = UiKit.Background;
        this.loginShell.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 46F));
        this.loginShell.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 54F));
        this.brandPanel.Dock = DockStyle.Fill;
        this.brandPanel.BackColor = UiKit.Navy;
        this.brandPanel.Padding = new Padding(56);
        this.brandLabel.Dock = DockStyle.Fill;
        this.brandLabel.Text = "S\nShieldBox\nControl analítico de caja\n\nProtegé el circuito de fondos con\nreglas claras, doble aprobación\ny evidencia auditable.";
        this.brandLabel.ForeColor = Color.White;
        this.brandLabel.BackColor = UiKit.Navy;
        this.brandLabel.Font = new Font("Segoe UI", 20F, FontStyle.Bold);
        this.brandPanel.Controls.Add(this.brandLabel);
        this.cardHostPanel.Dock = DockStyle.Fill;
        this.cardHostPanel.BackColor = UiKit.Background;
        this.cardHostPanel.Padding = new Padding(48);
        this.loginCard.Dock = DockStyle.Fill;
        this.loginCard.BackColor = Color.White;
        this.loginCard.Padding = new Padding(34);
        this.loginCard.BorderStyle = BorderStyle.FixedSingle;
        this.titleLabel.Dock = DockStyle.Top;
        this.titleLabel.Height = 42;
        this.titleLabel.Text = "Iniciar sesión";
        this.titleLabel.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
        this.titleLabel.ForeColor = UiKit.Ink;
        this.titleLabel.BackColor = Color.White;
        this.subtitleLabel.Dock = DockStyle.Top;
        this.subtitleLabel.Height = 32;
        this.subtitleLabel.Text = "Accedé con un usuario del circuito de control.";
        this.subtitleLabel.ForeColor = UiKit.Muted;
        this.subtitleLabel.BackColor = Color.White;
        this.userLabel.Dock = DockStyle.Top;
        this.userLabel.Height = 24;
        this.userLabel.Text = "Usuario";
        this.userLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        this.userLabel.ForeColor = UiKit.Muted;
        this.userLabel.BackColor = Color.White;
        this._login.Name = "loginTextBox";
        this._login.Dock = DockStyle.Top;
        this._login.Height = 32;
        this._login.Text = "mgarcia";
        this._login.PlaceholderText = "mgarcia";
        this.passwordLabel.Dock = DockStyle.Top;
        this.passwordLabel.Height = 24;
        this.passwordLabel.Text = "Contraseña";
        this.passwordLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        this.passwordLabel.ForeColor = UiKit.Muted;
        this.passwordLabel.BackColor = Color.White;
        this._password.Name = "passwordTextBox";
        this._password.Dock = DockStyle.Top;
        this._password.Height = 32;
        this._password.PlaceholderText = "demo123";
        this._password.UseSystemPasswordChar = true;
        this._error.Name = "errorLabel";
        this._error.Dock = DockStyle.Top;
        this._error.Height = 30;
        this._error.ForeColor = UiKit.Red;
        this._error.BackColor = Color.White;
        this.loginButton.Name = "loginButton";
        this.loginButton.Dock = DockStyle.Top;
        this.loginButton.Height = 48;
        this.loginButton.Text = "Ingresar al sistema";
        this.loginButton.BackColor = UiKit.Blue;
        this.loginButton.ForeColor = Color.White;
        this.loginButton.FlatStyle = FlatStyle.Flat;
        this.loginButton.FlatAppearance.BorderSize = 0;
        this.loginButton.Click += new EventHandler(this.LoginButton_Click);
        this.demoLabel.Dock = DockStyle.Top;
        this.demoLabel.Height = 32;
        this.demoLabel.Text = "Demo: mgarcia / demo123 · lfernandez / demo123 · jperez / demo123";
        this.demoLabel.Font = new Font("Segoe UI", 8F);
        this.demoLabel.ForeColor = UiKit.Muted;
        this.demoLabel.BackColor = Color.White;
        this.loginCard.Controls.Add(this.demoLabel);
        this.loginCard.Controls.Add(this.loginButton);
        this.loginCard.Controls.Add(this._error);
        this.loginCard.Controls.Add(this._password);
        this.loginCard.Controls.Add(this.passwordLabel);
        this.loginCard.Controls.Add(this._login);
        this.loginCard.Controls.Add(this.userLabel);
        this.loginCard.Controls.Add(this.subtitleLabel);
        this.loginCard.Controls.Add(this.titleLabel);
        this.cardHostPanel.Controls.Add(this.loginCard);
        this.loginShell.Controls.Add(this.brandPanel, 0, 0);
        this.loginShell.Controls.Add(this.cardHostPanel, 1, 0);
        this.Controls.Add(this.loginShell);
        this.AcceptButton = this.loginButton;
        this.AutoScaleMode = AutoScaleMode.Dpi;
        this.AutoScaleDimensions = new SizeF(96F, 96F);
        this.Text = "ShieldBox — Iniciar sesión";
        this.StartPosition = FormStartPosition.CenterScreen;
        this.MinimumSize = new Size(900, 560);
        this.ClientSize = new Size(1060, 680);
        this.BackColor = UiKit.Background;
        this.Font = new Font("Segoe UI", 9F);
        this.ResumeLayout(false);
    }
}
